### ISSUE TITLE
"Git was not detected on the path system"

### ISSUE THREAD

**Issue by EmilyForden** [cfss-old/fa16_hw01#20]
I had Git up and running with RStudio a few days ago, but not the path system is not detected. I'm reading the RStudio [help sheet](https://support.rstudio.com/hc/en-us/articles/200549016-Customizing-RStudio#version-control) but I haven't been able to redirect the path. 

Is it possible to just upload a PDF of my paper using the Git interface rather than remotely on my computer?

**Comment by bensoltoff** [comment]
Is this for Perspectives on Computational Analysis? You should be able to [upload a file through the Github.com interface](https://help.github.com/articles/adding-a-file-to-a-repository/). If you bring a printed copy of the paper to class today, that will also be sufficient.

In the future, try to submit issues to the correct class repo (I know it's sometimes confusing, but it helps me and Rick out if we know what class the issue is for)
